// routes/practiceRoutes.js
const express = require('express');
const auth = require('../middleware/authMiddleware');
const axios = require('axios');

const Unit = require('../models/Unit');
const Content = require('../models/Content');
const QuizQuestion = require('../models/QuizQuestion');
const Flashcard = require('../models/Flashcard');

const router = express.Router();

router.post('/generate/:unitId', auth('teacher'), async (req, res) => {
  try {
    const { unitId } = req.params;

    const unit = await Unit.findById(unitId);
    if (!unit) return res.status(404).json({ message: 'Unit not found' });

    const contents = await Content.find({ unit: unitId });
    if (!contents.length) {
      return res.status(400).json({ message: 'No content to generate from' });
    }

    // combine all text content for now
    const combinedText = contents
      .filter(c => c.type === 'text' && c.text)
      .map(c => c.text)
      .join('\n\n');

    if (!combinedText) {
      return res.status(400).json({ message: 'No text content available yet' });
    }

    // call Python microservice
    let pyRes;
    try {
      pyRes = await axios.post('http://127.0.0.1:8000/generate', {
        unitId,
        text: combinedText,
      });
    } catch (axiosErr) {
      console.error('Axios error calling Python service:', axiosErr.message);
      console.error('Python service response:', axiosErr.response?.data);
      throw new Error(`Python service error: ${axiosErr.response?.data?.detail || axiosErr.message}`);
    }


    const { quizQuestions, flashcards } = pyRes.data || {};

    const createdQuestions = [];
    if (Array.isArray(quizQuestions)) {
      for (const q of quizQuestions) {
        // Handle options - ensure it's an array
        let optionsArray = [];
        if (Array.isArray(q.options)) {
          optionsArray = q.options;
        } else if (typeof q.options === 'string') {
          // If options is a string, split it (fallback)
          optionsArray = q.options.split(/[|;,]/).map(o => o.trim()).filter(o => o);
        }
        
        const doc = await QuizQuestion.create({
          unit: unitId,
          questionType: q.type || 'mcq',
          questionText: q.question,
          options: optionsArray.map((optText, idx) => ({
            text: optText,
            isCorrect: idx === q.correctIndex,
          })),
          correctAnswerText:
            optionsArray && q.correctIndex != null
              ? optionsArray[q.correctIndex]
              : q.answer || '',
          difficulty: q.difficulty || 'easy',
          explanation: q.explanation || '', 
          isAutoGenerated: true,
        });
        createdQuestions.push(doc);
      }
    }

    const createdFlashcards = [];
    if (Array.isArray(flashcards)) {
      for (const card of flashcards) {
        const doc = await Flashcard.create({
          unit: unitId,
          front: card.front,
          back: card.back,
          isAutoGenerated: true,
        });
        createdFlashcards.push(doc);
      }
    }

    res.status(201).json({
      message: 'Practice generated from Python service',
      quizCount: createdQuestions.length,
      flashcardCount: createdFlashcards.length,
    });
  } catch (err) {
  console.error('Generate practice error FULL:', err.response?.data || err.message || err);
  res.status(500).json({ 
    message: 'Server error during generation',
    error: err.message,
    details: err.response?.data || 'No additional details'
  });
}
});
router.get('/quiz/:unitId', async (req, res) => {
  try {
    const { unitId } = req.params;
    const questions = await QuizQuestion.find({ unit: unitId }).sort({
      createdAt: -1,
    });
    res.json(questions);
  } catch (err) {
    console.error('Get quiz error:', err);
    res.status(500).json({ message: 'Server error' });
  }
});

router.get('/flashcards/:unitId', async (req, res) => {
  try {
    const { unitId } = req.params;
    const cards = await Flashcard.find({ unit: unitId }).sort({
      createdAt: -1,
    });
    res.json(cards);
  } catch (err) {
    console.error('Get flashcards error:', err);
    res.status(500).json({ message: 'Server error' });
  }
});

module.exports = router;
