// models/Flashcard.js
const mongoose = require('mongoose');

const flashcardSchema = new mongoose.Schema(
  {
    unit: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Unit',
      required: true,
    },
    front: {
      type: String,
      required: true,
      trim: true,  // question / term
    },
    back: {
      type: String,
      required: true,
      trim: true,  // answer / explanation
    },
    sourceContentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Content',
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Flashcard', flashcardSchema);
