// models/QuizQuestion.js
const mongoose = require('mongoose');

const quizQuestionSchema = new mongoose.Schema(
  {
    unit: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Unit',
      required: true,
    },
    questionType: {
      type: String,
      enum: ['mcq', 'true_false', 'fill_blank'],
      required: true,
    },
    questionText: {
      type: String,
      required: true,
      trim: true,
    },
    options: [
      {
        text: { type: String, trim: true },
        isCorrect: { type: Boolean, default: false },
      },
    ],
    correctAnswerText: {
      type: String,
      trim: true, // for true_false and fill_blank if needed
    },
    sourceContentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Content',
    },
    difficulty: {
      type: String,
      enum: ['easy', 'medium', 'hard'],
      default: 'easy',
    },
    // models/QuizQuestion.js
explanation: {
  type: String,
  trim: true,
},

    isAutoGenerated: {
      type: Boolean,
      default: true,
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model('QuizQuestion', quizQuestionSchema);
